[platformio]
src_dir = .

[env:esp32dev]
platform = espressif32
board = esp32dev
board_build.partitions = huge_app.csv
framework = arduino
monitor_speed = 115200

; Provide dependencies needed by esp32_feeder.ino
lib_deps =
    mobizt/Firebase ESP32 Client @ ^4.4.14
    madhephaestus/ESP32Servo @ ^3.0.5
